/*
==============================================================================
QUESTION
==============================================================================

Calculate the total sales for each product category.

*/

/*
==============================================================================
BUSINESS SCENARIO
==============================================================================

The sales team wants to analyze revenue generated by each product category to
identify the best-performing categories and support inventory and marketing
decisions.

Your task is to calculate the total sales amount for each category.

*/

/*
==============================================================================
CONCEPTS COVERED
==============================================================================

- SELECT
- SUM()
- GROUP BY
- Column Alias (AS)

*/

/*
==============================================================================
ASSUMED TABLE
==============================================================================

Table Name : Orders

Columns
--------
order_id
customer_id
category
order_date
quantity
total_amount

Sample Data
-----------

order_id | customer_id | category      | order_date | quantity | total_amount
------------------------------------------------------------------------------
5001     | 101         | Electronics   | 2026-07-01 | 2        | 2400.00
5002     | 102         | Furniture     | 2026-07-02 | 1        | 8500.00
5003     | 103         | Electronics   | 2026-07-03 | 3        | 4200.00
5004     | 104         | Stationery    | 2026-07-05 | 5        | 1250.00
5005     | 101         | Furniture     | 2026-07-06 | 1        | 5600.00
5006     | 105         | Electronics   | 2026-07-07 | 1        | 1800.00
5007     | 106         | Accessories   | 2026-07-08 | 4        | 2000.00
5008     | 102         | Stationery    | 2026-07-09 | 6        | 900.00

*/

/*
==============================================================================
SQL SOLUTION
==============================================================================
*/

SELECT
    category,
    SUM(total_amount) AS total_sales
FROM Orders
GROUP BY category;

/*
==============================================================================
EXPLANATION
==============================================================================

The GROUP BY clause groups rows that have the same value in the specified
column.

For each category, the SUM() function calculates the total sales amount.

Instead of returning one result for the entire table, SQL returns one summary
row for each product category.

*/

/*
==============================================================================
EXPECTED OUTPUT
==============================================================================

category      | total_sales
----------------------------
Accessories   | 2000.00
Electronics   | 8400.00
Furniture     | 14100.00
Stationery    | 2150.00

*/

/*
==============================================================================
BEST PRACTICES
==============================================================================

✓ Every non-aggregated column in the SELECT clause must also appear in the
  GROUP BY clause.

✓ Use meaningful aliases to improve report readability.

✓ Choose grouping columns that provide meaningful business insights.

*/

/*
==============================================================================
REAL-WORLD APPLICATIONS
==============================================================================

✓ Sales Performance Reports

✓ Product Category Analysis

✓ Executive Dashboards

✓ Inventory Planning

✓ Business Intelligence Reporting

*/

/*
==============================================================================
RELATED CONCEPTS
==============================================================================

Previous:
→ MAX()

Next:
→ HAVING
→ COUNT(DISTINCT)
→ Window Functions

*/
