/*
===============================================================================
QUESTION
===============================================================================

Build an Employee Performance Dashboard using SQL.

The HR department wants to evaluate employee performance based on sales,
orders handled, and revenue generated.

The analysis should answer the following questions:

1. How many orders has each employee handled?
2. What is the total revenue generated by each employee?
3. What is the average order value?
4. Rank employees based on revenue.
5. Classify employees into performance categories.
6. Identify the top-performing employees.

*/

/*
===============================================================================
BUSINESS SCENARIO
===============================================================================

RetailHub employs multiple sales representatives responsible for processing
customer orders.

The HR and Sales departments want a dashboard that measures employee
performance objectively using sales data.

The dashboard will be used during quarterly performance reviews,
bonus calculations, and promotion decisions.

*/

/*
===============================================================================
BUSINESS OBJECTIVE
===============================================================================

Generate employee KPIs including:

• Orders Processed
• Revenue Generated
• Average Order Value
• Revenue Rank
• Performance Category

*/

/*
===============================================================================
CONCEPTS COVERED
===============================================================================

• Aggregate Functions
• GROUP BY
• INNER JOIN
• CASE Statement
• CTE
• Window Functions
• DENSE_RANK()
• SUM()
• COUNT()
• AVG()

*/

/*
===============================================================================
ASSUMED TABLES
===============================================================================

Employees
---------

EmployeeID
FirstName
LastName
Department

Orders
------

OrderID
EmployeeID
CustomerID
OrderDate
TotalAmount

*/

/*
===============================================================================
SQL SOLUTION
===============================================================================
*/

WITH EmployeePerformance AS
(
    SELECT

        e.EmployeeID,

        CONCAT(e.FirstName,' ',e.LastName) AS EmployeeName,

        e.Department,

        COUNT(o.OrderID) AS OrdersProcessed,

        SUM(o.TotalAmount) AS RevenueGenerated,

        ROUND(AVG(o.TotalAmount),2) AS AverageOrderValue

    FROM Employees e

    JOIN Orders o

        ON e.EmployeeID = o.EmployeeID

    GROUP BY

        e.EmployeeID,
        e.FirstName,
        e.LastName,
        e.Department
)

SELECT

    EmployeeID,

    EmployeeName,

    Department,

    OrdersProcessed,

    RevenueGenerated,

    AverageOrderValue,

    CASE

        WHEN RevenueGenerated >= 1000000
            THEN 'Outstanding'

        WHEN RevenueGenerated >= 500000
            THEN 'Excellent'

        WHEN RevenueGenerated >= 200000
            THEN 'Good'

        ELSE 'Needs Improvement'

    END AS PerformanceCategory,

    DENSE_RANK()

        OVER
        (
            ORDER BY RevenueGenerated DESC
        ) AS RevenueRank

FROM EmployeePerformance

ORDER BY

    RevenueGenerated DESC;
