/*
==============================================================================
QUESTION
==============================================================================

Calculate the total revenue generated by different customer types using the
CASE statement.

*/

/*
==============================================================================
BUSINESS SCENARIO
==============================================================================

The sales team wants to understand how much revenue comes from different
customer segments.

Customers are categorized based on the total value of each order:

• Premium Customer : Order Amount ≥ 5,000
• Standard Customer : Order Amount between 2,000 and 4,999
• Basic Customer : Order Amount < 2,000

Your task is to classify each order and calculate the total revenue generated
by each customer type.

*/

/*
==============================================================================
CONCEPTS COVERED
==============================================================================

- CASE Statement
- Aggregate Functions
- SUM()
- GROUP BY
- Conditional Classification
- Business Reporting

*/

/*
==============================================================================
ASSUMED TABLE
==============================================================================

Table Name : Orders

Columns
--------
order_id
customer_name
order_amount

Sample Data
-----------

order_id | customer_name | order_amount
----------------------------------------
1001     | Rahul         | 6500
1002     | Priya         | 4200
1003     | Aman          | 1800
1004     | Neha          | 7200
1005     | Kavya         | 3100
1006     | Arjun         | 1500
1007     | Sneha         | 5800
1008     | Mohit         | 2600

*/

/*
==============================================================================
SQL SOLUTION
==============================================================================
*/

SELECT

    CASE
        WHEN order_amount >= 5000 THEN 'Premium Customer'
        WHEN order_amount >= 2000 THEN 'Standard Customer'
        ELSE 'Basic Customer'
    END AS customer_type,

    COUNT(*) AS total_orders,

    SUM(order_amount) AS total_revenue

FROM Orders

GROUP BY

    CASE
        WHEN order_amount >= 5000 THEN 'Premium Customer'
        WHEN order_amount >= 2000 THEN 'Standard Customer'
        ELSE 'Basic Customer'
    END

ORDER BY total_revenue DESC;

/*
==============================================================================
EXPLANATION
==============================================================================

Step 1:

Each order is classified into one of three customer types using the CASE
statement.

Step 2:

GROUP BY groups together all orders belonging to the same customer type.

Step 3:

COUNT(*) calculates the number of orders in each category.

Step 4:

SUM(order_amount) calculates the total revenue generated by each customer type.

The result provides a summarized business report instead of individual order
details.

*/

/*
==============================================================================
EXPECTED OUTPUT
==============================================================================

customer_type      | total_orders | total_revenue
-------------------------------------------------
Premium Customer   | 3            | 19500
Standard Customer  | 3            | 9900
Basic Customer     | 2            | 3300

*/

/*
==============================================================================
BEST PRACTICES
==============================================================================

✓ Use CASE before aggregation to create business categories.

✓ Keep classification rules consistent across reports.

✓ Use descriptive category names.

✓ Aggregate only after the classification is complete.

✓ Order summary reports by important business metrics.

*/

/*
==============================================================================
REAL-WORLD APPLICATIONS
==============================================================================

✓ Revenue Analysis

✓ Customer Segmentation

✓ Executive Sales Reports

✓ Power BI Data Models

✓ Marketing Analytics

*/

/*
==============================================================================
RELATED CONCEPTS
==============================================================================

Previous:
→ Grade Student Marks

Next:
→ Employee Salary Bands
→ Conditional Aggregation
→ CASE with AVG()
→ CASE with COUNT()

*/
