/*
==============================================================================
QUESTION
==============================================================================

Build a business KPI dashboard using CASE statements and conditional
aggregation.

*/

/*
==============================================================================
BUSINESS SCENARIO
==============================================================================

The management team wants a one-page dashboard that summarizes key business
metrics from customer orders.

For every order:

• Completed orders contribute to completed revenue.
• Pending orders contribute to pending revenue.
• Cancelled orders are counted separately.

The dashboard should display:

• Total Orders
• Completed Orders
• Pending Orders
• Cancelled Orders
• Completed Revenue
• Pending Revenue
• Average Order Value
• High Value Orders (Amount ≥ 10,000)

*/

/*
==============================================================================
CONCEPTS COVERED
==============================================================================

- CASE Statement
- Conditional Aggregation
- COUNT()
- SUM()
- AVG()
- Dashboard Queries
- Business KPIs

*/

/*
==============================================================================
ASSUMED TABLE
==============================================================================

Table Name : Orders

Columns
--------
order_id
customer_name
order_amount
order_status

Sample Data
-----------

order_id | customer_name | order_amount | order_status
-------------------------------------------------------
1001     | Rahul         | 15000        | Completed
1002     | Priya         | 8200         | Completed
1003     | Aman          | 4200         | Pending
1004     | Neha          | 6200         | Cancelled
1005     | Kavya         | 12500        | Completed
1006     | Arjun         | 3800         | Pending
1007     | Sneha         | 9800         | Completed
1008     | Mohit         | 18000        | Completed

*/

/*
==============================================================================
SQL SOLUTION
==============================================================================
*/

SELECT

    COUNT(*) AS total_orders,

    SUM(
        CASE
            WHEN order_status = 'Completed' THEN 1
            ELSE 0
        END
    ) AS completed_orders,

    SUM(
        CASE
            WHEN order_status = 'Pending' THEN 1
            ELSE 0
        END
    ) AS pending_orders,

    SUM(
        CASE
            WHEN order_status = 'Cancelled' THEN 1
            ELSE 0
        END
    ) AS cancelled_orders,

    SUM(
        CASE
            WHEN order_status = 'Completed'
            THEN order_amount
            ELSE 0
        END
    ) AS completed_revenue,

    SUM(
        CASE
            WHEN order_status = 'Pending'
            THEN order_amount
            ELSE 0
        END
    ) AS pending_revenue,

    ROUND(AVG(order_amount),2) AS average_order_value,

    SUM(
        CASE
            WHEN order_amount >= 10000 THEN 1
            ELSE 0
        END
    ) AS high_value_orders

FROM Orders;

/*
==============================================================================
EXPLANATION
==============================================================================

This query creates an executive dashboard in a single SQL statement.

Step 1:

COUNT(*) calculates the total number of orders.

Step 2:

CASE inside SUM() counts orders for each order status.

Step 3:

CASE inside SUM() calculates revenue generated by completed and pending
orders.

Step 4:

AVG() calculates the average order value across all orders.

Step 5:

Another CASE statement counts orders whose value is at least 10,000.

This technique is called Conditional Aggregation and is one of the most
important SQL skills for Data Analysts.

*/

/*
==============================================================================
EXPECTED OUTPUT
==============================================================================

total_orders | completed_orders | pending_orders | cancelled_orders |
---------------------------------------------------------------------
8            | 5                | 2              | 1

completed_revenue | pending_revenue | average_order_value | high_value_orders
----------------------------------------------------------------------------
63500             | 8000            | 9725.00             | 3

*/

/*
==============================================================================
BEST PRACTICES
==============================================================================

✓ Use conditional aggregation instead of multiple queries.

✓ Keep CASE expressions simple and readable.

✓ Return business-friendly KPI names.

✓ Use ROUND() for financial metrics.

✓ Calculate multiple KPIs in one query whenever possible.

*/

/*
==============================================================================
REAL-WORLD APPLICATIONS
==============================================================================

✓ Executive KPI Dashboards

✓ Power BI Data Sources

✓ Tableau Reports

✓ Sales Performance Monitoring

✓ Business Intelligence Reporting

✓ Monthly Revenue Reports

✓ E-commerce Analytics

*/

/*
==============================================================================
RELATED CONCEPTS
==============================================================================

Previous:
→ Order Priority Classification

Next:
→ Aggregate Functions
→ GROUP BY
→ Window Functions
→ Dashboard Reporting
→ Power BI KPI Cards

*/
